### ISSUE TITLE
Showing "Content Credentials unavailable or invalid" error on Leica photo

### ISSUE THREAD

**Issue by n8fr8** [digimarc-corp/c2pa-content-credentials-extension#17]
This photo is from a Leica M11-P with C2PA:
https://baseline.proofmode.org/ipfs/QmUXcukAgpQDHVfEWqQ1DDw2yutZtJsVyqmA9uZR59monf

However the error below is showing. We have seen this from some other files as well such as this one:
https://baseline.proofmode.org/ipfs/QmW92bBjzQmXRvS9viekeLCJJVAaJYgkSzhVsjZhswPuex?filename=1699236937031.jpg

![Screen Shot 2023-12-12 at 1 22 42 PM](https://github.com/digimarc-corp/c2pa-content-credentials-extension/assets/30851/91d604d1-78d2-4782-94cf-7ff4640d6324)

Both of these files work fine in the Verify tool:
https://contentcredentials.org/verify?source=https://baseline.proofmode.org/ipfs/QmUXcukAgpQDHVfEWqQ1DDw2yutZtJsVyqmA9uZR59monf
https://contentcredentials.org/verify?source=https://baseline.proofmode.org/ipfs/QmW92bBjzQmXRvS9viekeLCJJVAaJYgkSzhVsjZhswPuex

**Comment by clementh59** [comment]
Hi, thanks for raising the issue.

We are aware of this bug and relayed it to the team behind the library we use to read manifests: https://github.com/contentauth/c2pa-js/issues/125

**Comment by domguinard** [comment]
Thanks a lot for reporting this @n8fr8 - adding a few other links where we experience the same issue:
https://truepic.com/truepic-sign/ (truck picture, bottom left)

**Comment by domguinard** [comment]
@n8fr8 happy to let you know that this issue has finally been resolved, sorry for the delay but this was a hard nut to crack. It was due to one of the crypto library not working properly in a sandbox. We now have moved away from using a sandbox. Many thanks for your report.
