### ISSUE TITLE
On demand validation

### ISSUE THREAD

**Issue by domguinard** [digimarc-corp/c2pa-content-credentials-extension#30]
The idea of this feature is to add an option to allow validation to be "on-demand" rather than automatic. With this feature the extension would not systematically try to find and validate manifests but the user would click on the image to ask for manifest check and validation.

**Comment by PercheEtienne** [comment]
New Feature: You will see `Verify image with C2PA` by right-clicking on an image on any website. If you click on it, it will verify the single image, and it will display the CR icon if the image has a manifest

<img width="838" alt="Screen Shot 2024-01-05 at 4 34 19 PM" src="https://github.com/digimarc-corp/c2pa-content-credentials-extension/assets/47390745/77a92ff9-a292-44cb-8555-067a52644abf">
